version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/stop_apache
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/start_apache
      timeout: 300
      runas: root
